tags:
- CITY
summary: "Delete City"
description: "This is a simple API which deletes city"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "path"
  name: "city_id"
  type: "integer"
  required: true
  schema:
    type: "object"
    properties: 
      name:
        type: "string"
responses:
  200:
    description: "Country"
  400:
    description: "Bad request"
  404:
    description: "Invalid input"