summary: "Delete City"
description: "This is a simple API which deletes city"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "path"
  name: "id"
  type: "integer"
  schema:
    type: "object"
    properties: 
      name:
        type: "string"
responses:
  200:
    description: "City"
  500:
    description: "Invalid input"