summary: "Post City"
description: "This is a simple API which posts city"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "path"
  name: "country_id"
  type: "integer"
  required: true
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties: 
      name:
        type: "string"
responses:
  200:
    description: "Country"
  500:
    description: "Invalid input"